pipelines:
  branches:
    UAT:
      - step:
          name: Deploy to nowa stg
          script:
            - echo "Deploying to UAT"
            - pipe: atlassian/ssh-run:0.7.1
              variables:
                SSH_USER: $SSH_USER  
                SERVER: $SERVER_IP
                PORT: $PORT
                COMMAND: "bash /var/www/script/nowa-tarality.sh"
            - echo "Deployment complete."